version: "0"
  
services:
  #database
  caffeinecounterdatabase:
    image:  mongo:latest
    container_name: CaffeineCounterDB
    ports:
      #revist ports for something thats not default
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      - MONGO_PORT = ${MONGO_PORT}
      - MONGO_INITDB_ROOT_USERNAME = ${MONGO_INITDB_ROOT_USERNAME} 
      - MONGO_INITDB_ROOT_PASSWORD = ${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE =  ${MONGO_INITDB_DATABASE}
    env_file:
      - .env
    expose:
      - ${MONGO_PORT}:${MONGO_PORT}
  #mongo ui 
  db-express:
    image: mongo-express
    container_name: caffeinecounterdb-express
    ports: 
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME = ${MONGO_INITDB_ROOT_USERNAME} 
      - ME_CONFIG_MONGODB_ADMINPASSWORD = ${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGODB_EXPRESS_URL}
    depends_on:
      - caffeinecounterdatabase
